### ISSUE TITLE
[Tooltip]: shadow doesn't disappear in Safari

### ISSUE THREAD

**Issue by veiko-kapp** [TEHIK-EE/tedi-design-system#243]
https://smjira.sm.ee/browse/UPP-2499

Safari sisselogimata avalehele keelevaliku drop-down jääb avatuks peale keele vahetamist:
![image-2024-10-02-09-02-09-029](https://github.com/user-attachments/assets/94bc60a8-04a7-488c-9714-21e684e66fa3)

**Comment by kasparsuvi1** [comment]
The shadow is different now:

**Comment by kasparsuvi1** [comment]
Shadow doesn't match how it was previously. Before it was larger and because of that the arrow of tooltip stands more out.

The shadow before:
![image](https://github.com/user-attachments/assets/e0b04a72-705b-4fc2-8a23-60e52badb7c1)

Shadow now:
![image](https://github.com/user-attachments/assets/a716b7d4-7b96-4ccb-8510-f8478e8c9478)
